#!/bin/bash

function ai() { 
    (
    dir_path="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
    cd $dir_path
    edcv # activate venv
    COMMAND_PATH=$dir_path/ai.py
    python $COMMAND_PATH $@
    )
}
